const searchActionTypes = {
  QUERY_MOVIE_START: "QUERY_MOVIE_START",
  QUERY_MOVIE_SUCCESS: "QUERY_MOVIE_SUCCESS",
  QUERY_MOVIE_FAILURE: "QUERY_MOVIE_FAILURE",
};

export default searchActionTypes;
