const searchActionTypes = {
  QUERY_MOVIE_START: "QUERY_MOVIE_START",
  QUERY_MOVIE_SUCCESS: "QUERY_MOVIE_SUCCESS",
  QUERY_MOVIE_FAILURE: "QUERY_MOVIE_FAILURE",

  LOAD_MORE_MOVIES_START: "LOAD_MORE_MOVIES",
  LOAD_MORE_MOVIES_SUCCESS: "LOAD_MORE_SUCCESS",
  LOAD_MORE_MOVIES_FAILURE: "LOAD_MORE_FAILURE",

  HAS_MORE_MOVIES: "HAS_MORE_MOVIES",
};

export default searchActionTypes;
