const moviesActionTypes = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  CHANGE_RELEVANCE: "CHANGE_RELEVANCE",
};

export default moviesActionTypes;
