const moviesActionTypes = {
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  CHANGE_RELEVANCE: "CHANGE_RELEVANCE",

  LOAD_MORE_MOVIES_START: "LOAD_MORE_MOVIES",
  LOAD_MORE_MOVIES_SUCCESS: "LOAD_MORE_SUCCESS",
  LOAD_MORE_MOVIES_FAILURE: "LOAD_MORE_FAILURE",

  HAS_MORE_MOVIES: "HAS_MORE_MOVIES",

  SET_SORT_FILTER: "SET_SORT_FILTER",
  SET_GENRE_FILTER: "SET_GENRE_FILTER",
  SET_YEAR_FILTER: "SET_GENRE_FILTER",
};

export default moviesActionTypes;
