const genreActionTypes = {
  FETCH_MOVIE_BY_GENRE_START: "FETCH_MOVIE_BY_GENRE_START",
  FETCH_MOVIE_BY_GENRE_SUCCESS: "FETCH_MOVIE_BY_GENRE_SUCCESS",
  FETCH_MOVIE_BY_GENRE_FAILURE: "FETCH_MOVIE_BY_GENRE_FAILURE",

  FETCH_GENRES_START: "FETCH_GENRES_START",
  FETCH_GENRES_SUCCESS: "FETCH_GENRES_SUCCESS",
  FETCH_GENRES_FAILURE: "FETCH_GENRES_FAILURE",
};

export default genreActionTypes;
