const discoverActionTypes = {
  FETCH_DISCOVER_START: "FETCH_DISCOVER_START",
  FETCH_DISCOVER_SUCCESS: "FETCH_DISCOVER_SUCCESST",
  FETCH_DISCOVER_FAILURE: "FETCH_DISCOVER_FAILURE",
};

export default discoverActionTypes;
