const discoverActionTypes = {
  FETCH_DISCOVER_START: "FETCH_DISCOVER_START",
  FETCH_DISCOVER_SUCCESS: "FETCH_DISCOVER_SUCCESST",
  FETCH_DISCOVER_FAILURE: "FETCH_DISCOVER_FAILURE",

  LOAD_MORE_MOVIES_DISCOVER_START: "LOAD_MORE_MOVIES_DISCOVER_START",
  LOAD_MORE_MOVIES_DISCOVER_SUCCESS: "LOAD_MORE_MOVIES_DISCOVER_SUCCESS",
  LOAD_MORE_MOVIES_DISCOVER_FAILURE: "LOAD_MORE_MOVIES_DISCOVER_FAILURE",

  HAS_MORE_DISCOVER_MOVIES: "HAS_MORE_MOVIES",
};

export default discoverActionTypes;
